sudo: false
dist: trusty

language: python
python:
  - 3.6
  - 3.7

cache:
  pip: true

addons:
  apt:
    packages:
      - libopenbabel-dev
      - swig

before_install:
  - pip install -r requirements.txt

install:
  - pip install .

script:
  - nosetests -v
