packages:
  # TODO: add DALTON (not available through Open Babel)
  ADF:
    boilerplate: |+
      TITLE {{ molecules[0].title }}

      CHARGE {{ molecules[0].charge }}  {{ molecules[0].spin - 1 }}

      Number of atoms
       {{ molecules[0].atoms|count }}

      ATOMS Cartesian
      {{ xyz(molecules[0]) }}
      End

      Basis
      End

      Geometry
      End



  GAMESS:
    boilerplate: |+1
      $CONTRL COORD=CART UNITS=ANGS $END

      $DATA
     {{ molecules[0].title }}
     C1
     {{ xyz(molecules[0], style="GAMESS") }}
      $END



  GAMESSUK:
    boilerplate: |+
      {{ molecules[0].write('gukin') }}
  # Gaussian:
    # boilerplate: |+
      # {{ molecules[0].write('gzmat') }}
  Gaussian:
    boilerplate: |+
      #Put Keywords Here, check Charge and Multiplicity.

       {{ molecules[0].title }}

      {{ molecules[0].charge }}  {{ molecules[0].spin }}
      {{ xyz(molecules[0]) }}


  Jaguar:
    boilerplate: |+
      {{ molecules[0].write('jin') }}
  Molpro:
    boilerplate: |+
      {{ molecules[0].write('mp') }}
  # MOPAC:
    # boilerplate: |+
      # {{ molecules[0].write('mopin') }}
  MOPAC:
    boilerplate: |+
      CHARGE={{ molecules[0].charge }} MS={{ (molecules[0].spin - 1)/2 }}
      {{ molecules[0].title }}

      {{ xyz(molecules[0], style="MOPAC") }}

  MPQC:
    boilerplate: |+
      {{ molecules[0].write('mpqcin') }}
  NWChem:
    boilerplate: |+
      start molecule

      title {{ molecules[0].title }}

      geometry units angstroms print xyz autosym
      {{ xyz(molecules[0]) }}
      end

  ORCA:
    boilerplate: |+
      # {{ molecules[0].title }}
      ! Opt

      * xyz {{ molecules[0].charge }} {{ molecules[0].spin }}
      {{ xyz(molecules[0]) }}
      *

  Psi:
    boilerplate: |+
      # {{ molecules[0].title }}

      molecule {
      {{ molecules[0].charge }} {{ molecules[0].spin }}
      {{ xyz(molecules[0]) }}
      units angstrom
      }

      optimize('scf')
  QChem:
    boilerplate: |+
      {{ molecules[0].write('qcin') }}
  ZINDO:
    boilerplate: |+
      {{ molecules[0].write('zin') }}
